routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index')->name('index');

/** Staff **/
Route::prefix('staff')->as('staff.')->group(function () {
    Route::get('/', 'StaffController@index')->name('index');
    Route::get('/create', 'StaffController@create')->name('create');
    Route::post('/', 'StaffController@store')->name('store');
    Route::get('/{staff}/edit', 'StaffController@edit')->name('edit');
    Route::patch('/{staff}', 'StaffController@update')->name('update');
    Route::delete('/{staff}', 'StaffController@destroy')->name('delete');
});

/** Main Slider **/
Route::prefix('sliders')->as('sliders.')->group(function () {
    Route::get('/', 'SlidersController@index')->name('index');
    Route::get('create', 'SlidersController@create')->name('create');
    Route::post('/', 'SlidersController@store')->name('store');
    Route::get('{slider}/edit', 'SlidersController@edit')->name('edit');
    Route::patch('/{slider}', 'SlidersController@update')->name('update');
    Route::delete('/{slider}', 'SlidersController@destroy')->name('delete');
});

/** Gallery Images **/
Route::prefix('gallery')->as('gallery.')->group(function () {
    Route::get('/', 'GalleryController@index')->name('index');
    Route::get('create', 'GalleryController@create')->name('create');
    Route::post('/', 'GalleryController@store')->name('store');
    Route::get('{gallery}/edit', 'GalleryController@edit')->name('edit');
    Route::patch('/{gallery}', 'GalleryController@update')->name('update');
    Route::delete('/{gallery}', 'GalleryController@destroy')->name('delete');
});

/** Posts **/
Route::prefix('posts')->as('posts.')->group(function () {
    Route::get('/', 'PostsController@index')->name('index');
    Route::get('create', 'PostsController@create')->name('create');
    Route::post('/', 'PostsController@store')->name('store');
    Route::get('{post}/edit', 'PostsController@edit')->name('edit');
    Route::patch('/{post}', 'PostsController@update')->name('update');
    Route::delete('/{post}', 'PostsController@destroy')->name('delete');
});

/** Courses **/
Route::prefix('courses')->as('courses.')->group(function () {
    /** Introduction **/
    Route::prefix('intro')->as('intro.')->group(function(){
        Route::get('edit', 'CoursesIntroductionController@edit')->name('edit');
        Route::patch('/', 'CoursesIntroductionController@update')->name('update');
    });

    /** Diploma **/
    Route::prefix('diploma')->as('diploma.')->group(function(){
        Route::get('edit', 'CoursesDiplomaController@edit')->name('edit');
        Route::patch('/', 'CoursesDiplomaController@update')->name('update');
    });
    
    Route::get('/', 'CoursesController@index')->name('index');
    Route::get('create', 'CoursesController@create')->name('create');
    Route::post('/', 'CoursesController@store')->name('store');
    Route::get('{course}/edit', 'CoursesController@edit')->name('edit');
    Route::patch('/{course}', 'CoursesController@update')->name('update');
    Route::delete('/{course}', 'CoursesController@destroy')->name('delete');


    /** Attachments **/
    Route::prefix('{course}/attachments')->as('attachments.')->group(function () {
        Route::get('/', 'CourseAttachmentsController@index')->name('index');
        Route::post('/', 'CourseAttachmentsController@store')->name('store');
        Route::delete('/{attachment}', 'CourseAttachmentsController@destroy')->name('delete');
    });
});

/** Guests **/
Route::prefix('guests')->as('guests.')->group(function () {
    Route::get('/', 'GuestsController@index')->name('index');
    Route::get('create', 'GuestsController@create')->name('create');
    Route::post('/', 'GuestsController@store')->name('store');
    Route::get('{guest}/edit', 'GuestsController@edit')->name('edit');
    Route::patch('/{guest}', 'GuestsController@update')->name('update');
    Route::delete('/{guest}', 'GuestsController@destroy')->name('delete');
});

Route::namespace('Auth')->group(function(){
    // Authentication Routes...
    $this->get('login', 'LoginController@showLoginForm')->name('login');
    $this->post('login', 'LoginController@login');
    $this->get('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...
    $this->get('register', 'RegisterController@showRegistrationForm')->name('register');
    $this->post('register', 'RegisterController@register');

    // Password Reset Routes...
    $this->get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    $this->post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    $this->get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    $this->post('password/reset', 'ResetPasswordController@reset');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();
// Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'HomepageController@index')->name('homepage');
Route::get('/about-us', 'AboutPageController@index')->name('about-us');

Route::get('/gallery', 'GalleryController@index')->name('gallery.index');

Route::get('/contact-us', 'ContactUsController@create')->name('contact-us.create');
Route::post('/contact-us', 'ContactUsController@store')->name('contact-us.store');

Route::get('/posts', 'PostsController@index')->name('posts.index');
Route::get('/posts/{post}', 'PostsController@show')->name('posts.show');

Route::get('/staff', 'StaffController@index')->name('staff.index');
Route::get('/staff/{staff}', 'StaffController@show')->name('staff.show');

Route::get('/courses', 'CoursesController@index')->name('courses.index');
Route::get('/courses/intro', 'CoursesController@intro')->name('courses.intro');
Route::get('/courses/diploma', 'CoursesController@diploma')->name('courses.diploma');
Route::get('/courses/{course}', 'CoursesController@show')->name('courses.show');

Route::get('/newsletter/activate-email/{code}', 'NewsletterSubscribersController@activateEmail')->name('newsletter.activate-email');

app/Models/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
	use SoftDeletes;
	
	protected $guarded = [];
	
	public function getFormattedCreatedAtAttribute()
	{	
		return $this->created_at->format('Y-M-d H:i');
	}

	public function url($relative = true)
	{
		if (! $relative) {
			return route('posts.show', ['post' => $this->id]);
		}

		return route('posts.show', ['post' => $this->id], false);
	}

	public function getImageUrlAttribute()
    {
    	return Storage::disk('images')->url($this->image);
    }

    public function excerpt($chars = 70)
    {
        return str_limit(
            html_entity_decode(
                strip_tags($this->body)
            ), 
            $chars
        );
    }

    public function scopePublished($query)
    {
    	return $query->where('published', 1);
    }
}

app/Http/Controllers/AdminControllers/PostsController.php
<?php

namespace App\Http\Controllers\AdminControllers;

use App\Post;
use App\Jobs\OptimizeImage;
use Facades\App\ImageStore;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class PostsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin')->except('logout');
    }

    public function index()
    {
        return view('admin.posts.index')->with('posts', Post::orderBy('created_at', 'desc')->paginate(10));
    }

    public function create()
    {
        return view('admin.posts.add');
    }

    public function store(Request $request)
    {
        $validated_inputs = $this->validate($request, [
            'title' => 'required|max:255',
            'body' => 'required',
            'published' => 'boolean',
            'image' => 'required',
        ]);
        
        $post = Post::create(array_merge(
            $validated_inputs, 
            [
                'image' => ImageStore::moveRequestImageTo('posts'),
                'slug' => str_slug($request->title),
            ]
        ));

        OptimizeImage::dispatch($post->image);

        return redirect()->route('admin.posts.index');
    }

    public function edit($id)
    {
        $post = Post::find($id);
        return view('admin.posts.edit',compact('post'));
    }

    public function update(Request $request, Post $post)
    {
        $validated_inputs = $this->validate($request, [
            'title' => 'required|max:255',
            'body' => 'required',
            'published' => 'boolean',
        ]);

        if (! empty($request->image)) {
            ImageStore::delete($post->image);
            $image = ['image' => ImageStore::moveRequestImageTo('posts')];

            OptimizeImage::dispatch($image['image']);
        } else {
            $image = [];
        }

        $post->fill(
            array_merge(
                $validated_inputs, 
                $image
            )
        )->save();

        return redirect()->route('admin.posts.index');
    }

    public function destroy(Post $post)
    {
        $post->delete();
        return redirect()->route('admin.posts.index');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Post;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('posts.index', [
            'posts' => Post::latest()->published()->paginate(10)
        ]);
    }

    public function show($post)
    {
        $post = Post::published()->findOrFail($post);

        return view('posts.show')->with('post', $post);
    }
}

resources/views/posts/index.blade.php
@extends('includes.master')
@section('title', 'لائحة الأخبار والفعاليّات')
@section('keyword','رؤيا , أكاديمية، تدريب، إعلامي، أخبار، أحداث، نشاطات، فعاليّات')
@section('description','أكاديمية رؤيا  للتدريب الإعلامي')

@section('content')
    <div class="inner-page">
        <!-- Posts Section Start Here -->
		<div class="blog-page-area sec-spacer">
			<div class="container">
                <!-- Posts -->
                <div class="row">
                    @if(count($posts) > 0)
                    @foreach ($posts as $post)
                        <div class="col-lg-6 col-md-12">
                            <div class="row mb-30 blog-inner">
                                <div class="col-lg-6 col-md-12">
                                    <a href="{{ $post->url() }}" title="{{ $post->title }}">
                                        <div class="blog-images">
                                            <i class="fa fa-link" aria-hidden="true"></i>
                                            <img src="{{ $post->image_url }}" alt="{{ $post->title }}" title="{{ $post->title }}">
                                        </div>
                                    </a>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="blog-content">
                                        <div class="date">
                                            <i class="fa fa-calendar-check-o"></i> {{ $post->formatted_created_at }}
                                        </div>
                                        <h4>
                                            <a href="{{ $post->url() }}" title="{{ $post->title }}">{{ str_limit($post->title,50) }}</a>
                                        </h4>
                                        {!! $post->excerpt(50) !!}
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                    @else
                        <div class="col-lg-12">
                            <p>سنوافيكم بأحدث أخبارنا وفعالياتنا قريباً</p>
                        </div>
                    @endif
                </div>

                {{ $posts->links() }}
			</div>
		</div>
        <!-- Posts End  -->
    </div>
@endsection

resources/views/posts/show.blade.php
@extends('includes.master')
@section('title', $post->title)
@section('keyword','رؤيا , أكاديمية، تدريب، إعلامي، أخبار، أحداث، فعاليات')
@section('description','أكاديمية رؤيا  للتدريب الإعلامي')

@section('content')
    <div class="inner-page">
		<div class="single-blog-details sec-spacer">
			<div class="container">
				<div class="row">
					<!-- Post Block Start -->
					<div class="col-lg-8 col-md-12">
						<!-- Post Title -->
						<h1 class="top-title">{{ $post->title }}</h1>
						<!-- Post Title End -->

						<!-- Post Image -->
						<div class="single-image">
							<img src="{{ $post->image_url }}" alt="{{ $post->title }}" title="{{ $post->title }}">
						</div>
						<!-- Post Image End -->

						<!-- Publish Date -->
						<div class="date mb-15">
							<i class="fa fa-calendar" aria-hidden="true"></i> نشر: {{ $post->formatted_created_at }}
						</div>
						<!-- Publish Date End -->

						<!-- Post Body -->
						<div class="desc-text">
							{!! $post->body !!}
						</div>
						<!-- Post Body End -->

						{{-- <!-- Post Tags Block -->
						<div class="share-section">
							<div class="row">
								<div class="col-lg-12">
									<ul class="share-link1">
										<li><a href="#"> الأوسمة:</a></li>
										<li><a href="#"> Building</a></li>
										<li><a href="#"> Plumbing</a></li>
										<li><a href="#"> Painting</a></li>
									</ul>
								</div>
							</div>
						</div>
						<!-- Post Tags Block End --> --}}

						<!-- Post Sharing Block -->
						{{-- <div class="share-section2">
							<div class="row">
								<div class="col-lg-6 col-md-6 col-sm-12">
									<div class="share-label"> قم بمشاركة الخبر: </div>
								</div>
								<div class="col-lg-6 col-md-6 col-sm-12">
									<ul class="share-link">
										<li><a href="#"> <i class="fa fa-facebook" aria-hidden="true"></i> Facebook</a></li>
										<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i> Twitter</a></li>
										<li><a href="#"><i class="fa fa-google" aria-hidden="true"></i> Google</a></li>
									</ul>
								</div>
							</div>
						</div> --}}
						<!-- Post Sharing Block End -->
					</div>
					<!-- Post Block End -->

					<!-- Left Side -->
					<div class="col-lg-4 col-md-12">
						<div class="sidebar-area">
							@include ('includes.latest-courses')
						</div>
					</div>
					<!-- Left Side -->
				</div>
			</div>
		</div>
    </div>
@endsection